//
// voices
// to use... const voices = require('./voices');
//

const voices = [
  {name: 'Alex', locale: 'en_US', sample: `Most people recognize me by my voice.`},
  {name: 'Alice', locale: 'it_IT', sample: `Salve, mi chiamo Alice e sono una voce italiana.`},
  {name: 'Alva', locale: 'sv_SE', sample: `Hej, jag heter Alva. Jag är en svensk röst.`},
  {name: 'Amelie', locale: 'fr_CA', sample: `Bonjour, je m’appelle Amelie. Je suis une voix canadienne.`},
  {name: 'Anna', locale: 'de_DE', sample: `Hallo, ich heiße Anna und ich bin eine deutsche Stimme.`},
  {name: 'Carmit', locale: 'he_IL', sample: `שלום. קוראים לי כרמית, ואני קול בשפה העברית.`},
  {name: 'Damayanti', locale: 'id_ID', sample: `Halo, nama saya Damayanti. Saya berbahasa Indonesia.`},
  {name: 'Daniel', locale: 'en_GB', sample: `Hello, my name is Daniel. I am a British-English voice.`},
  {name: 'Diego', locale: 'es_AR', sample: `Hola, me llamo Diego y soy una voz española.`},
  {name: 'Ellen', locale: 'nl_BE', sample: `Hallo, mijn naam is Ellen. Ik ben een Belgische stem.`},
  {name: 'Fiona', locale: 'en-scotland', sample: `Hello, my name is Fiona. I am a Scottish-English voice.`},
  {name: 'Fred', locale: 'en_US', sample: `I sure like being inside this fancy computer`},
  {name: 'Ioana', locale: 'ro_RO', sample: `Bună, mă cheamă Ioana . Sunt o voce românească.`},
  {name: 'Joana', locale: 'pt_PT', sample: `Olá, chamo-me Joana e dou voz ao português falado em Portugal.`},
  {name: 'Jorge', locale: 'es_ES', sample: `Hola, me llamo Jorge y soy una voz española.`},
  {name: 'Juan', locale: 'es_MX', sample: `Hola, me llamo Juan y soy una voz mexicana.`},
  {name: 'Kanya', locale: 'th_TH', sample: `สวัสดีค่ะ ดิฉันชื่อKanya`},
  {name: 'Karen', locale: 'en_AU', sample: `Hello, my name is Karen. I am an Australian-English voice.`},
  {name: 'Kyoko', locale: 'ja_JP', sample: `こんにちは、私の名前はKyokoです。日本語の音声をお届けします。`},
  {name: 'Laura', locale: 'sk_SK', sample: `Ahoj. Volám sa Laura . Som hlas v slovenskom jazyku.`},
  {name: 'Lekha', locale: 'hi_IN', sample: `नमस्कार, मेरा नाम लेखा है. मैं हिन्दी में बोलने वाली आवाज़ हूँ.`},
  {name: 'Luca', locale: 'it_IT', sample: `Salve, mi chiamo Luca e sono una voce italiana.`},
  {name: 'Luciana', locale: 'pt_BR', sample: `Olá, o meu nome é Luciana e a minha voz corresponde ao português que é falado no Brasil`},
  {name: 'Maged', locale: 'ar_SA', sample: `مرحبًا اسمي Maged. أنا عربي من السعودية.`},
  {name: 'Mariska', locale: 'hu_HU', sample: `Üdvözlöm! Mariska vagyok. Én vagyok a magyar hang.`},
  {name: 'Mei-Jia',locale: 'zh_TW', sample: `您好，我叫美佳。我說國語。`},
  {name: 'Melina', locale: 'el_GR', sample: `Γεια σας, ονομάζομαι Melina. Είμαι μια ελληνική φωνή.`},
  {name: 'Milena', locale: 'ru_RU', sample: `Здравствуйте, меня зовут Milena. Я – русский голос системы.`},
  {name: 'Moira', locale: 'en_IE', sample: `Hello, my name is Moira. I am an Irish-English voice.`},
  {name: 'Monica', locale: 'es_ES', sample: `Hola, me llamo Monica y soy una voz española.`},
  {name: 'Nora', locale: 'nb_NO', sample: `Hei, jeg heter Nora. Jeg er en norsk stemme.`},
  {name: 'Paulina', locale: 'es_MX', sample: `Hola, me llamo Paulina y soy una voz mexicana.`},
  {name: 'Samantha', locale: 'en_US', sample: `Hello, my name is Samantha. I am an American-English voice.`},
  {name: 'Sara', locale: 'da_DK', sample: `Hej, jeg hedder Sara. Jeg er en dansk stemme.`},
  {name: 'Satu', locale: 'fi_FI', sample: `Hei, minun nimeni on Satu. Olen suomalainen ääni.`},
  {name: 'Sin-ji', locale: 'zh_HK', sample: `您好，我叫 Sin-ji。我講廣東話。`},
  {name: 'Tessa', locale: 'en_ZA', sample: `Hello, my name is Tessa. I am a South African-English voice.`},
  {name: 'Thomas', locale: 'fr_FR', sample: `Bonjour, je m’appelle Thomas. Je suis une voix française.`},
  {name: 'Ting-Ting', locale: 'zh_CN', sample: `您好，我叫Ting-Ting。我讲中文普通话。`},
  {name: 'Veena', locale: 'en_IN', sample: `Hello, my name is Veena. I am an Indian-English voice.`},
  {name: 'Victoria', locale: 'en_US', sample: `Isn't it nice to have a computer that will talk to you?`},
  {name: 'Xander', locale: 'nl_NL', sample: `Hallo, mijn naam is Xander. Ik ben een Nederlandse stem.`},
  {name: 'Yelda', locale: 'tr_TR', sample: `Merhaba, benim adım Yelda. Ben Türkçe bir sesim.`},
  {name: 'Yuna', locale: 'ko_KR', sample: `안녕하세요. 제 이름은 Yuna입니다. 저는 한국어 음성입니다.`},
  {name: 'Yuri', locale: 'ru_RU', sample: `Здравствуйте, меня зовут Yuri. Я – русский голос системы.`},
  {name: 'Zosia', locale: 'pl_PL', sample: `Witaj. Mam na imię Zosia, jestem głosem kobiecym dla języka polskiego.`},
  {name: 'Zuzana', locale: 'cs_CZ', sample: `Dobrý den, jmenuji se Zuzana. Jsem český hlas.`},
];

module.exports = voices;
